// next/atomic/atom/input-number/index.tsx
import { InputNumber } from 'primereact/inputnumber'
import type { JSX } from 'react'

import styles from './index.module.scss'
import type { InputNumberInterface } from './types'

export function AdInputNumber({
  className = '',
  nuiType,
  ...rest
}: InputNumberInterface): JSX.Element {
  const cx = (...classes: (string | undefined | null | false)[]) =>
    classes.filter(Boolean).join(' ')

  const pt = {
    root: {
      className: cx(styles['ad-inputnumber'], className),
    },
    input: {
      root: {
        className: styles['ad-inputtext'],
        ...(nuiType ? { 'nui-type': nuiType } : {}),
      },
    },
  }

  return <InputNumber {...rest} pt={pt} />
}

// nuxt/atomic/atom/input-number/index.vue
<template>
  <InputNumber
    v-bind="transformProps(props)"
    :class="$style['ad-inputnumber']"
    :pt="{
      pcInputText: {
        root: {
          class: $style['ad-inputtext'],
          'nui-type': props.nuiType,
        } 
      },
    }"
  >
    <slot />
  </InputNumber>
</template>

<script setup lang="ts">
import type { InputNumberInterface } from '.'

import { transformProps } from '../../boson/transform_props'

const props = defineProps<InputNumberInterface>()
</script>

<style lang="scss" module>
@import 'index';
</style>
