// next/atomic/molecule/tile/index.tsx
'use client'
import Link from 'next/link'
import type { JSX } from 'react'

import styles from './index.module.scss'
import type { TileInterface } from './types'

import { AdIcon } from '../../atom/icon'
import { AdParagraph } from '../../atom/paragraph'

export function AdTile({
  adType,
  header,
  href = '#',
  count,
  countSecondary,
  textSecondary,
  icon,
}: TileInterface): JSX.Element {
  return (
    <Link href={href} data-ad-type={adType} className={styles['ad-tile']}>
      <div className={styles['general']}>
        <div className={styles['info']}>
          <div className={styles['header']}>
            <AdParagraph text={header} />
          </div>

          <div className={styles['count']}>
            <AdParagraph text={count !== undefined ? String(count) : ''} />
          </div>
        </div>

        <div className={styles['icon-container']}>
          <AdIcon className={styles['icon']} icon={icon} adType={adType} />
        </div>
      </div>

      <div className={styles['secondary']}>
        <div className={styles['count']}>
          <AdParagraph
            text={countSecondary !== undefined ? `${countSecondary} new` : ''}
          />
        </div>
        <div className={styles['text']}>
          <AdParagraph text={textSecondary} />
        </div>
      </div>
    </Link>
  )
}

// nuxt/components/molecule/tile/index.vue
<template>
  <ad-anchor class="tile my-card" :href="props.href" :ad-type="props.adType">
    <div class="general">
      <div class="info">
        <atom-paragraph class="header" :text="props.header" />
        <atom-paragraph class="count" :text="props.count" />
      </div>
      <ad-icon class="icon" :icon="props.icon" :ad-type="props.adType" />
    </div>
    <div class="secondary">
      <atom-paragraph class="count" :text="props.countSecondary + ' new'" />
      <atom-paragraph class="text" :text="props.textSecondary" />
    </div>
  </ad-anchor>
</template>

<script setup lang="ts">
import { TileInterface } from '.'

const props = defineProps<TileInterface>()
</script>
