// nuxt/atomic/organism/accordion/index.vue
<template>
  <Accordion 
    v-bind="transformProps(props, excludedProps)"
    :class="$style['ad-accordion']"
  >
    <AccordionPanel
      v-for="(panel, index) in props.panels"
      :key="index"
      :value="panel.index"
      :class="$style['ad-accordionpanel']"
    >
      <AccordionHeader
        :class="$style['ad-accordionheader']"
        :pt="{
          toggleIcon: $style['ad-accordionheader-toggle-icon'],
        }"
      >
        <nuc-animation-hexagons 
          v-if="props.hexagons" 
          :class="$style['ad-hexagon-rows-container']"
        />
        {{ panel.content }}
      </AccordionHeader>
      <AccordionContent 
        :class="$style['ad-accordion-content']"
      >
        {{ panel.answer }}
      </AccordionContent>
    </AccordionPanel>
    <slot />
  </Accordion>
</template>

<script setup lang="ts">
import type { AccordionInterface } from '.'

import { transformProps } from '../../boson/transform_props'

const props = defineProps<AccordionInterface>()

const excludedProps = ['panels', 'hexagons']
</script>

<style lang="scss" module>
@import 'index';
</style>

// next/atomic/organism/accordion/index.tsx
'use client'

import { Accordion, AccordionTab } from 'primereact/accordion'
import type { ReactNode } from 'react'

import styles from './index.module.scss'

import type { AccordionInterface } from './types/interfaces'

export function AdAccordion({
  panels,
  hexagons,
  className = '',
  ...rest
}: AccordionInterface): ReactNode {
  const cx = (...classes: (string | undefined | null | false)[]) =>
    classes.filter(Boolean).join(' ')

  const pt = {
    container: {
      root: { className: styles['ad-accordion'] },
    },
    item: {
      root: { className: styles['ad-accordionpanel'] },
      header: { className: styles['ad-accordionheader'] },
      headerAction: { className: styles['ad-accordionheader-action'] },
      headerIcon: { className: styles['ad-accordionheader-toggle-icon'] },
      content: { className: styles['ad-accordion-content'] },
    },
  }

  const hasPanels = panels && panels.length > 0

  return (
    hasPanels && (
      <Accordion
        {...rest}
        className={cx(styles['ad-accordion'], className)}
        pt={pt.container}
      >
        {panels.map((panel, index) => (
          <AccordionTab
            key={index}
            pt={pt.item}
            header={
              <>
                {hexagons && (
                  <div className={styles['ad-hexagon-rows-container']} />
                )}
                {panel.content}
              </>
            }
          >
            {panel.answer}
          </AccordionTab>
        ))}
      </Accordion>
    )
  )
}
