// next/atomic/atom/button/index.tsx
import { Button, type ButtonProps } from 'primereact/button'
import type { CSSProperties, JSX, ReactNode } from 'react'

import styles from './index.module.scss'
import type { ButtonInterface } from './types'
import { AdIcon } from '../icon'
import { AdImage } from '../image'

export function AdButton({
  adType,
  media,
  variant,
  rounded,
  severity,
  width,
  height,
  gap,
  padding,
  label,
  icon,
  src,
  alt,
  children,
  className = '',
  style,
  ...rest
}: ButtonInterface & { children?: ReactNode }): JSX.Element {
  const isPrimary = (severity as string) === 'primary'
  const primeSeverity = isPrimary
    ? undefined
    : (severity as ButtonProps['severity'])

  const cx = (...classes: (string | undefined | null | false)[]) =>
    classes.filter(Boolean).join(' ')

  const pt = {
    root: {
      className: cx(
        styles['ad-button'],
        icon && styles['with-ad-icon'],
        media && styles[`${media}-button`],
        variant && styles[`${variant}-button`],
        rounded && styles['rounded-button'],
        isPrimary && styles['primary-button'],
        className
      ),
      style: {
        width,
        height,
        gap,
        padding,
        ...style,
      } as CSSProperties,
      ...(adType ? { 'ad-type': adType } : {}),
    },
    label: {
      className: styles['p-button-label'],
    },
    icon: {
      className: styles['prime-icon'],
    },
  }

  return (
    <Button
      {...rest}
      aria-label={rest['aria-label'] ?? label}
      severity={primeSeverity}
      rounded={rounded}
      pt={pt}
    >
      {src && <AdImage src={src} alt={alt} />}
      {icon && <AdIcon icon={icon} />}
      {label ? <span className={styles['p-button-label']}>{label}</span> : null}
      {children}
    </Button>
  )
}

// nuxt/atomic/atom/button/index.vue
<template>
  <Button
    v-bind="transformProps(props, excludedProps)"
    :style="{
      width: props.width,
      gap: props.gap,
      padding: props.padding,
    }"
    :class="[
      $style['ad-button'],
      props.media && $style[props.media + '-button'],
      props.variant && $style[props.variant + '-button'],
      props.rounded && $style['rounded-button'],
      props.severity === 'primary' && $style['primary-button'],
    ]"
  >
    <ad-image v-if="props.src" :src="props.src" :alt="props.alt" />
    <ad-icon v-if="props.icon" :icon="props.icon" />
    <template v-if="props.label">{{ $t(props.label, props.label) }}</template>
    <slot />
  </Button>
</template>

<script setup lang="ts">
import type { ButtonInterface } from '.'

import { transformProps } from '../../boson/transform_props'

const props = defineProps<ButtonInterface>()

const excludedProps = [
  'alt',
  'label',
  'icon',
  'src',
  'width',
  'height',
  'gap',
  'padding',
]
</script>

<style lang="scss" module>
@import 'index';
</style>
