// next/atomic/atom/spacing/index.tsx
import type { JSX } from 'react'

import styles from './index.module.scss'
import type { SpacingInterface } from './types'

export function AdSpacing({
  className,
  size = 'normal',
}: SpacingInterface = {}): JSX.Element {
  const sizeClass = size === 'normal' ? undefined : styles[`ad-spacing-${size}`]

  return (
    <div
      className={[styles['ad-spacing'], sizeClass, className]
        .filter(Boolean)
        .join(' ')}
      aria-hidden="true"
    />
  )
}

// nuxt/atomic/atom/spacing/index.vue
<template>
  <div
    class="ad-spacing"
    :class="[props.class, sizeClass]"
    aria-hidden="true"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue'

import type { SpacingInterface } from './types'

const props = withDefaults(defineProps<SpacingInterface>(), {
  size: 'normal',
})

const sizeClass = computed(() =>
  props.size === 'normal' ? undefined : `ad-spacing-${props.size}`
)
</script>

<style lang="scss">
@import 'index';
</style>
