// nuxt/pages/[lang]/dev/[...slug].vue
<template>
  <div v-if="page" :id="page.id">
    <nuc-grid-background v-if="page.grid" />
    <component :is="page.component" />
  </div>
  <nuc-error-404-page v-else />
</template>

<script setup lang="ts">
import { computed, resolveComponent } from 'vue'

const route = useRoute()

const slug = computed(() => {
  const parts = route.params.slug
  return Array.isArray(parts) ? parts.join('/') : String(parts ?? '')
})

const pageMap: Record<string, { id: string; grid: boolean }> = {
  offer: { id: 'offer', grid: true },
  'about-us': { id: 'about-us', grid: true },
  process: { id: 'process-page', grid: true },
  services: { id: 'services', grid: true },
  'services/business-websites': { id: 'business-websites', grid: true },
  'services/ecommerce-stores': { id: 'ecommerce-stores', grid: true },
  'services/landing-pages': { id: 'landing-pages', grid: true },
  'services/website-redesign': { id: 'website-redesign', grid: true },
  'services/custom-projects': { id: 'custom-projects', grid: true },
  'privacy-policy': { id: 'privacy-policy', grid: false },
  'terms-of-service': { id: 'terms-of-service', grid: false },
  cookies: { id: 'cookies', grid: false },
  gdpr: { id: 'gdpr', grid: false },
}

const page = computed(() => {
  const entry = pageMap[slug.value]
  if (!entry) return null

  const componentName = `nuc-${entry.id}-page`
  return {
    ...entry,
    component: resolveComponent(componentName),
  }
})
</script>

// next/app/[lang]/dev/[...slug]/page.tsx
'use client'

import { useParams } from 'next/navigation'
import type { ComponentType, JSX } from 'react'

import {
  DEV_PAGE_MAP,
  NucAboutUsPage,
  NucBusinessWebsitesPage,
  NucCookiesPage,
  NucCustomProjectsPage,
  NucEcommerceStoresPage,
  NucError404Page,
  NucGDPRPage,
  NucGridBackground,
  NucLandingPagesPage,
  NucOfferPage,
  NucPrivacyPolicyPage,
  NucProcessPage,
  NucServicesPage,
  NucTermsOfServicePage,
  NucWebsiteRedesignPage,
} from 'nucleify'

const DEV_PAGE_COMPONENTS: Record<string, ComponentType> = {
  offer: NucOfferPage,
  'about-us': NucAboutUsPage,
  'process-page': NucProcessPage,
  services: NucServicesPage,
  'business-websites': NucBusinessWebsitesPage,
  'ecommerce-stores': NucEcommerceStoresPage,
  'landing-pages': NucLandingPagesPage,
  'website-redesign': NucWebsiteRedesignPage,
  'custom-projects': NucCustomProjectsPage,
  'privacy-policy': NucPrivacyPolicyPage,
  'terms-of-service': NucTermsOfServicePage,
  cookies: NucCookiesPage,
  gdpr: NucGDPRPage,
}

export default function DevPreviewPage(): JSX.Element {
  const params = useParams()
  const slugParts = params?.slug
  const slug = Array.isArray(slugParts)
    ? slugParts.join('/')
    : String(slugParts ?? '')

  const entry = DEV_PAGE_MAP[slug]
  if (!entry) {
    return <NucError404Page />
  }

  const Page = DEV_PAGE_COMPONENTS[entry.id]
  if (!Page) {
    return <NucError404Page />
  }

  return (
    <div id={entry.id}>
      {entry.grid ? <NucGridBackground /> : null}
      <Page />
    </div>
  )
}
