// atomic/molecules/Anchor/index.vue
<template>
  <a
    :href="props.href"
    :rel="props.rel"
    :target="props.target"
    :style="props.style"
  >
    <slot />
    <ad-icon v-if="props.icon" :icon="props.icon" />
    <ad-image
      v-if="props.src"
      :src="props.src"
      :alt="props.label"
      :fetchpriority="props.fetchpriority"
    />
    <ad-label
      v-if="props.label"
      :label="props.label"
      :style="{ cursor: 'pointer' }"
    />
  </a>
</template>

<script setup lang="ts">
import { AnchorInterface } from 'atomic'

const props = defineProps<AnchorInterface>()
</script>

// next/atomic/molecule/anchor/index.tsx
import type { JSX, ReactNode } from 'react'

import type { AnchorInterface } from './types'

import { AdIcon, AdImage, AdLabel } from '../../atom'

export function AdAnchor({
  children,
  href,
  rel,
  target,
  style,
  icon,
  adType,
  size,
  src,
  alt,
  fetchpriority,
  label,
  anchorClass,
  itemClass,
  tooltip,
  ...rest
}: AnchorInterface & { children?: ReactNode }): JSX.Element {
  const combinedStyle = { cursor: 'pointer', ...(style ?? {}) }
  return (
    <a href={href} rel={rel} target={target} style={combinedStyle} {...rest}>
      {children}
      {icon && <AdIcon icon={icon} adType={adType} size={size} />}
      {src && <AdImage src={src} alt={alt} fetchpriority={fetchpriority} />}
      {label && <AdLabel label={label} />}
    </a>
  )
}
