// next/atomic/organism/data-table/index.tsx
import { DataTable } from 'primereact/datatable'
import type { JSX } from 'react'

import styles from './index.module.scss'

import { adTypePt } from '../../utils/ad_type'
import selectStyles from '../select/index.module.scss'
import type { DataTableInterface } from './types/interfaces'

export function AdDataTable({
  className = '',
  adType,
  value,
  loading,
  rows = 10,
  paginator = true,
  showHeaders = true,
  stripedRows = true,
  rowHover = true,
  filters,
  onFilter,
  children,
  ...rest
}: DataTableInterface): JSX.Element | null {
  if (!value || loading) return null

  const cx = (...classes: (string | undefined | null | false)[]) =>
    classes.filter(Boolean).join(' ')

  const adTypeAttribute = adType ? { 'ad-type': adType } : {}

  const pt = {
    root: {
      className: cx(styles['ad-datatable'], className),
      'data-nuc-datatable': '',
      ...adTypePt(adType)?.root,
    },
    bodyRow: {
      className: styles['ad-datatable-row'],
    },
    headerContent: {
      className: styles['ad-datatable-column-header-content'],
    },
    paginator: {
      root: {
        className: cx(
          styles['ad-datatable-paginator-bottom'],
          styles['ad-datatable-paginator']
        ),
      },
      firstPageButton: {
        className: styles['ad-datatable-paginator-first'],
      },
      prevPageButton: {
        className: styles['ad-datatable-paginator-prev'],
      },
      nextPageButton: {
        className: styles['ad-datatable-paginator-next'],
      },
      lastPageButton: {
        className: styles['ad-datatable-paginator-last'],
      },
      current: {
        className: styles['ad-datatable-paginator-current'],
      },
      RPPDropdown: {
        root: {
          className: cx(
            selectStyles['ad-select'],
            styles['ad-datatable-paginator-rpp']
          ),
          ...adTypeAttribute,
        },
        input: {
          className: selectStyles['ad-select-label'],
        },
        trigger: {
          className: selectStyles['ad-select-dropdown'],
        },
        panel: {
          className: selectStyles['ad-select-overlay'],
          ...adTypeAttribute,
        },
        wrapper: {
          className: selectStyles['ad-select-list-container'],
        },
        list: {
          className: selectStyles['ad-select-list'],
        },
        item: {
          className: selectStyles['ad-select-option'],
        },
      },
    },
  }

  return (
    // PrimeReact DataTable props union is overly strict when spreading `rest` with `pt`
    // @ts-expect-error — cellSelection overload mismatch with spread
    <DataTable
      {...rest}
      value={value}
      rows={rows}
      paginator={paginator}
      showHeaders={showHeaders}
      stripedRows={stripedRows}
      rowHover={rowHover}
      filters={filters}
      onFilter={onFilter}
      pt={pt}
      {...adTypeAttribute}
    >
      {children}
    </DataTable>
  )
}

// nuxt/atomic/organism/data-table/index.vue
<template>
  <DataTable
    v-if="props.value && !props.loading"
    v-bind="transformProps(props, excludedProps)"
    v-model:filters="props.filters"
    @update:filters="emits('update:filters', $event)"
    :rows="props.rows || 10"
    :paginator="props.paginator || true"
    :show-headers="props.showHeaders|| true"
    :striped-rows="props.stripedRows || true"
    :row-hover="props.rowHover || true"
    :pt="{
      root: $style['ad-datatable'],
      bodyRow: $style['ad-datatable-row'],
      columnHeaderContent: $style['ad-datatable-column-header-content'],
      pcPaginator: {
        paginatorContainer: $style['ad-datatable-paginator-bottom'],
        root: $style['ad-datatable-paginator'],
        content: $style['ad-datatable-paginator-content'],
        first: $style['ad-datatable-paginator-first'],
        prev: $style['ad-datatable-paginator-prev'],
        current: $style['ad-datatable-paginator-current'],
        next: $style['ad-datatable-paginator-next'],
        last: $style['ad-datatable-paginator-last'],
        pcRowPerPageDropdown: {
          root: {
            class: $style['ad-select'], 
            'ad-type': props.adType
          },
          label: $style['ad-select-label'],
          dropdown: $style['ad-select-dropdown'],
          overlay: {
            class: $style['ad-select-overlay'],
            'ad-type': props.adType,
          },
          listContainer: $style['ad-select-list-container'],
          list: $style['ad-select-list'],
          option: $style['ad-select-option'],
        },
      }
    }"
  >
    <slot />
  </DataTable>
</template>

<script setup lang="ts">
import type { DataTableInterface } from 'atomic'

import { transformProps } from '../../boson/transform_props'

const props = defineProps<DataTableInterface>()
const emits = defineEmits<{ (e: 'update:filters', value: unknown): void }>()

const excludedProps = [
  'loading',
  'actions',
  'openDialog',
  'selectedObject',
  'rows',
]
</script>

<style lang="scss" module>
@import 'index';
</style>
