// nuxt/atomic/molecule/tile/index.vue
<template>
  <nuxt-link 
    :class="$style['ad-tile']"
    :to="props.href" 
    :ad-type="props.adType"
    class="ad-tile"
  >
    <div :class="$style['general']">
      <div :class="$style['info']">
        <ad-paragraph :class="$style['header']" :text="props.header" />
        <ad-paragraph :class="$style['count']" :text="props.count" />
      </div>
      <div :class="$style['icon-container']">
        <ad-icon 
          :class="$style['icon']" 
          :icon="props.icon" 
          :ad-type="props.adType" 
          :storybook="props.storybook" 
        />
      </div>
    </div>
    <div :class="$style['secondary']">
      <ad-paragraph :class="$style['count']" :text="props.countSecondary + ' new'" />
      <ad-paragraph :class="$style['text']" :text="props.textSecondary" />
    </div>
  </nuxt-link>
</template>

<script setup lang="ts">
import type { TileInterface } from '.'

import { AdIcon, AdParagraph } from '../../atom' // Import for Storybook

const props = defineProps<TileInterface>()
</script>

<style lang="scss" module>
@import 'index';
</style>

// next/atomic/molecule/tile/index.tsx
'use client'
import Link from 'next/link'
import type { JSX } from 'react'

import styles from './index.module.scss'
import type { TileInterface } from './types'

import { AdIcon } from '../../atom/icon'
import { AdParagraph } from '../../atom/paragraph'

export function AdTile({
  adType,
  header,
  href = '#',
  count,
  countSecondary,
  textSecondary,
  icon,
}: TileInterface): JSX.Element {
  return (
    <Link href={href} data-ad-type={adType} className={styles['ad-tile']}>
      <div className={styles['general']}>
        <div className={styles['info']}>
          <div className={styles['header']}>
            <AdParagraph text={header} />
          </div>

          <div className={styles['count']}>
            <AdParagraph text={count !== undefined ? String(count) : ''} />
          </div>
        </div>

        <div className={styles['icon-container']}>
          <AdIcon className={styles['icon']} icon={icon} adType={adType} />
        </div>
      </div>

      <div className={styles['secondary']}>
        <div className={styles['count']}>
          <AdParagraph
            text={countSecondary !== undefined ? `${countSecondary} new` : ''}
          />
        </div>
        <div className={styles['text']}>
          <AdParagraph text={textSecondary} />
        </div>
      </div>
    </Link>
  )
}
