// next/atomic/organism/tree/index.tsx
'use client'

import { Tree } from 'primereact/tree'
import type { JSX } from 'react'

import type { AdTreeNode, TreeInterface } from './types'

function renderTreeNode(node: AdTreeNode): JSX.Element {
  if (node.type === 'url' && node.data) {
    return (
      <a href={String(node.data)} className={node.className}>
        {node.label}
      </a>
    )
  }

  return <b className={node.className}>{node.label}</b>
}

export function AdTree({ className, ...rest }: TreeInterface): JSX.Element {
  return (
    <Tree
      {...rest}
      className={[className, 'ad-tree'].filter(Boolean).join(' ')}
      nodeTemplate={renderTreeNode}
    />
  )
}

// nuxt/atomic/organism/tree/index.vue
<template>
  <Tree v-bind="transformProps(props)">
    <template #default="slotProps">
      <b :class="slotProps.node.class">{{ slotProps.node.label }}</b>
    </template>
    <template #url="slotProps">
      <a :href="slotProps.node.data" :class="slotProps.node.class">{{ slotProps.node.label }}</a>
    </template>
  </Tree>
</template>

<script setup lang="ts">
import type { TreeInterface } from '.'

import { transformProps } from '../../boson/transform_props'

const props = defineProps<TreeInterface>()
</script>
