// next/atomic/organism/select/index.tsx
'use client'

import { Dropdown } from 'primereact/dropdown'
import { type JSX, useEffect, useState } from 'react'

import styles from './index.module.scss'

import type { SelectInterface } from './types/interfaces'

function useAppendTarget(
  appendTo: SelectInterface['appendTo']
): HTMLElement | undefined {
  const [target, setTarget] = useState<HTMLElement | undefined>(undefined)

  useEffect(() => {
    if (appendTo === null) {
      setTarget(undefined)
      return
    }

    if (appendTo === undefined || appendTo === 'body') {
      setTarget(document.body)
      return
    }

    if (typeof appendTo === 'string') {
      setTarget(document.querySelector(appendTo) as HTMLElement | undefined)
      return
    }

    setTarget(appendTo)
  }, [appendTo])

  return target
}

export function AdSelect({
  className,
  nuiType,
  appendTo,
  ...rest
}: SelectInterface): JSX.Element {
  const cx = (...classes: (string | undefined | null | false)[]) =>
    classes.filter(Boolean).join(' ')

  const appendTarget = useAppendTarget(appendTo ?? 'body')

  const pt = {
    root: {
      className: cx(styles['ad-select'], className),
      ...(nuiType ? { 'nui-type': nuiType } : {}),
    },
    input: {
      className: styles['ad-select-label'],
    },
    trigger: {
      className: styles['ad-select-dropdown'],
    },
    panel: {
      className: styles['ad-select-overlay'],
      ...(nuiType ? { 'nui-type': nuiType } : {}),
    },
    wrapper: {
      className: styles['ad-select-list-container'],
    },
    list: {
      className: styles['ad-select-list'],
    },
    item: {
      className: styles['ad-select-option'],
    },
  }

  return <Dropdown {...rest} appendTo={appendTarget} pt={pt} />
}

// nuxt/atomic/organism/select/index.vue
<template>
  <Select
    v-bind="transformProps(props)"
    :class="$style['ad-select']"
    appendTo="body"
    :pt="{
      label: $style['ad-select-label'],
      dropdown: $style['ad-select-dropdown'],
      overlay: {
        class: $style['ad-select-overlay'],
        'nui-type': props.nuiType,
      },
      listContainer: $style['ad-select-list-container'],
      list: $style['ad-select-list'],
      option: $style['ad-select-option'],
    }"
    @update:model-value="onUpdateModelValue"
  >
    <slot />
  </Select>
</template>

<script setup lang="ts">
import type { SelectInterface } from '.'

import { transformProps } from '../../boson/transform_props'

const props = defineProps<SelectInterface>()
const emit = defineEmits(['update:modelValue'])

function onUpdateModelValue(value: unknown) {
  emit('update:modelValue', value)
}
</script>

<style lang="scss" module>
@import 'index';
</style>
